name: Deploy Next.js Client MinhtuAuthentic to VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4

      # Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      # Cài đặt dependencies và build
      - name: Install and Build
        run: |
          yarn install
          yarn run build

      # Triển khai lên VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd /var/www/minhtuauthentic-page

            git remote set-url origin git@github.com:hoanghuydev/minhtuauthentic-page.git
            git pull origin develop

            yarn install
            yarn run build

            pm2 restart minhtuauthentic-page || pm2 start npm --name "minhtuauthentic-page" -- start
